### PR TITLE
(bug): Extensions Not Showing Up

### PR DESCRIPTION
**Pull request by jasonbahl**
This fixes a bug where the assets for the GraphiQL Extensions (Auth Switch / Composer) were enqueued in the wrong order and not executing properly.

### CODE REVIEW

**Comment by justlevine** [comment]
Confirmed working 
image

**Comment by jasonbahl** [comment]
@justlevine sweet! 

I'm still not sure why the button text is black on the "Add New Query" and "Add New Mutation" buttons. 

Likely similar issue, but with the style assets? 🤔  👀

**Comment by jasonbahl** [comment]
It's weird, though, the button text is white for me, before and after this bugfix. 🤔 

Can you maybe inspect the CSS on those buttons and screenshot what you see in the devtools for why the text is black?

They should look like: 

Screen Shot 2021-12-06 at 10 59 42 AM

**Comment by justlevine** [comment]
seems the specificty of `.graphiql-container button` wins out over `.ant-btn-primary`

image

**Comment by jasonbahl** [comment]
Ah ha! I see. 

And I know why it's different on my machine and yours 🤦🏻‍♂️ . 

I'll work on the fix. Thanks for the screenshot. 🙌🏻

**Comment by jasonbahl** [comment]
@justlevine the black button text should be resolved now. I'll get this merged and released. 

Thanks! 🙏🏻

**Comment by jasonbahl** [comment]
@justlevine aside: what browser are you on? 

All those scrollbars are making me cringe! 😆

**Pull request merged**
